### ISSUE TITLE
interventions.csv data updates

### ISSUE THREAD

**Issue by gunnarsundberg** [JieYingWu/COVID-19_US_County-level_Summaries#166]
It looks like data in the file `interventions.csv` has not been updated since July 9th. Are there plans to continue updating this data?

**Comment by paulinarebo** [comment]
Hello, I have the same question. Is there any plan of updating the NPI data? Thanks

**Comment by JieYingWu** [comment]
Thanks for all the interest in our project. As the vaccine rollout seems promising in curbing COVID, we have stopped efforts in gathering NPI data for now. Since this project was supported completely through volunteer efforts in collecting the data from each county government/news source, it was not envisioned to be a continuous effort, but only to bridge the immediate gap in information we saw.
